### ISSUE TITLE
Cross shows up when first opening Terminal

### ISSUE THREAD

**Issue by jkdf2** [nimiq/promptastic#16]
Whenever I open the Terminal, Gnome Terminal, I get a 'x' indicating a non-zero exit code. Why do I get this with a fresh Terminal?

**Comment by nimiq** [comment]
This is probably not related to Promptastic. I suggest you to disable Promptastic and see if you get the same error.

In order to do so, follow these steps:
- In you `~/.bashrc` comment our the lines added by Promptastic:   
  `# function _update_ps1() { export PS1="$(/.../promptastic.py $?)"; }`   
  `# export PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"`   
   This will disable Promptastic.
-  Close and restart your terminal. Now you won't see any cross of course, but to inspect what the exit code is, run:   
`echo $?`   
If you get a number different than 0, then this is the proof that the error is not cause by Promptastic.
In this there is probably an error in your  `~/.bashrc` or `~/.bash_profile`.

**Comment by jkdf2** [comment]
First off, thank you for your work on this truly fantastic featured prompt.

Secondly, you're right. I am still getting `1` anytime I use the "Open Folder in Terminal" feature of my desktop environment, even with promptastic disabled. When I open the Terminal via the normal shortcut, everything works as expected. Appears to be a bug in my desktop environment (Cinnamon). Thanks for your help in diagnosing it.
